name: Robot Framework - Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-datadriver
          pip install -U robotframework-datadriver[XLS]
          pip install yagmail

      - name: Test with RobotFramework
        run: robot .

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Report
          path: report.html
      
      - name: Download Test Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: Report
          path: .

      - name: Send Test Report via Email
        if: success() || failure()
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          python -c "
          import os
          import yagmail

          sender_email = 'anilkumarsingh142200@gmail.com'
          receiver_email = 'rathoretushar01@gmail.com'
          subject = 'Robot Framework Test Report'

          # Retrieve the app-specific password from the environment variable
          app_password = os.getenv('GMAIL_APP_PASSWORD')

          # Initialize the Yagmail client
          yag = yagmail.SMTP(user=sender_email, password=app_password)

          # Path to the report file (using the correct path)
          report_path = './Report/report.html'
          # Print the current working directory for debugging
          print('Current working directory:', os.getcwd())

          # Check if the report file exists
          if os.path.exists(report_path):
              print(f'Report found: {report_path}')
              
              # Send the email
              print('Sending email...')
              yag.send(
                  to=receiver_email,
                  subject=subject,
                  contents='Please find the attached Robot Framework test report.\n\n# Additional information',
                  attachments=report_path  # Path to the report file
              )
              print('Email sent successfully')
          else:
              print(f'Report not found at path: {report_path}')
          "
